# Generated by Django 5.2.6 on 2026-01-10 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_remove_recitationsurahtrack_surah_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceversion",
            name="storage_url",
            field=models.FileField(
                blank=True,
                help_text="File storage for resource version",
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "txt", "zip", "tar", "gz", "json", "xml", "csv"]
                    )
                ],
            ),
        ),
    ]
