# Generated by Django 5.2.14 on 2026-08-12 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_alter_asset_is_open_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecitationFolder',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(help_text="Folder/variant name e.g. 'Clear', 'With echo', '128kbps'", max_length=255)),
                ('name_en', models.CharField(help_text="Folder/variant name e.g. 'Clear', 'With echo', '128kbps'", max_length=255, null=True)),
                ('name_ar', models.CharField(help_text="Folder/variant name e.g. 'Clear', 'With echo', '128kbps'", max_length=255, null=True)),
                ('slug', models.SlugField(allow_unicode=True, default='', help_text='URL-friendly slug, unique per asset. Used as the ?folder= API query value.')),
                ('is_default', models.BooleanField(default=False, help_text='The folder served when the API caller does not specify one. Exactly one per asset.')),
                ('asset', models.ForeignKey(help_text='Parent Asset representing the recitation set', on_delete=django.db.models.deletion.CASCADE, related_name='recitation_folders', to='content.asset')),
            ],
        ),
        migrations.AddField(
            model_name='recitationsurahtrack',
            name='folder',
            field=models.ForeignKey(help_text='Folder (variant) this track belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='content.recitationfolder'),
        ),
        migrations.AddIndex(
            model_name='recitationfolder',
            index=models.Index(fields=['asset', 'slug'], name='content_rec_asset_i_664f9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='recitationfolder',
            constraint=models.UniqueConstraint(fields=('asset', 'slug'), name='folder_unique_slug_per_asset'),
        ),
        migrations.AddConstraint(
            model_name='recitationfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('asset',), name='folder_one_default_per_asset'),
        ),
    ]
